=== BACSHOW/Lucera2-Java25/game/data/items/item.dtd
<!ELEMENT list (weapon|etcitem|armor)*>
<!ELEMENT weapon  (set|equip|for|enchant4_skill|cond|skills|triggers|attributes|enchant_options)*>
<!ATTLIST weapon
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>
<!ELEMENT etcitem (set|equip|for|enchant4_skill|cond|skills|triggers|enchant_options)*>
<!ATTLIST etcitem
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>
<!ELEMENT armor  (set|equip|for|enchant4_skill|cond|skills|triggers|attributes|enchant_options)*>
<!ATTLIST armor
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>

<!ELEMENT enchant_options (level)*>
<!ELEMENT level (option)*>
<!ATTLIST level
	val CDATA #REQUIRED>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
	id CDATA #REQUIRED>

<!ELEMENT equip (slot)*>
<!ELEMENT slot (#PCDATA)>
<!ATTLIST slot
	id CDATA #REQUIRED>

<!ELEMENT cond (player|target|using|zone|or|not|and)*>
<!ATTLIST cond
	msgId CDATA #IMPLIED
	addName CDATA #IMPLIED>
<!ELEMENT or (player|target|using|zone|not|and)*>
<!ELEMENT not (player|target|using|zone|or|and)*>
<!ELEMENT and (player|target|using|zone|or|not)*>
<!ELEMENT player (#PCDATA)>
<!ATTLIST player
	residence CDATA #IMPLIED
	olympiad CDATA #IMPLIED
	on_pvp_event CDATA #IMPLIED
	is_in_combat CDATA #IMPLIED
	race CDATA #IMPLIED
	instance_zone CDATA #IMPLIED
	classId CDATA #IMPLIED
    minLevel CDATA #IMPLIED
    maxLevel CDATA #IMPLIED
	is_hero  CDATA #IMPLIED
	maxPK  CDATA #IMPLIED
	min_pledge_rank  CDATA #IMPLIED
	castleId  CDATA #IMPLIED
	is_clan_leader  CDATA #IMPLIED
	is_in_academy  CDATA #IMPLIED
    gender CDATA #IMPLIED>
<!ELEMENT target (#PCDATA)>
<!ATTLIST target
	pvp CDATA #REQUIRED>
<!ELEMENT using (#PCDATA)>
<!ATTLIST using
	slotitem CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	type CDATA #REQUIRED>

<!ELEMENT for (add|set|mul|enchant)*>
<!ELEMENT add (player|target|using|zone|or|not|and)*>
<!ATTLIST add
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT attributes (attribute)*>
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute
	element CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT mul (player|target|using|zone)*>
<!ATTLIST mul
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT set (player|target|using|zone|or|not|and)*>
<!ATTLIST set
	name CDATA #IMPLIED
	order CDATA #IMPLIED
	stat CDATA #IMPLIED
	value CDATA #REQUIRED>

<!ELEMENT enchant (#PCDATA)>
<!ATTLIST enchant
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT enchant4_skill (#PCDATA)>
<!ATTLIST enchant4_skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>

<!ELEMENT skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>

<!ELEMENT triggers (trigger)*>
<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	type CDATA #REQUIRED
	chance CDATA #REQUIRED>

=== BACSHOW/Lucera2-Java25/game/data/items/SHIELD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">

<list>
 	<weapon id="9400" name="Dusk Shield">
    <!-- [Dusk Shield] -->
    <set name="crystal_count" value="188"/>
    <set name="crystal_type" value="S"/>
    <set name="crystallizable" value="true"/>
    <set name="icon" value="Old_ShieldIcons.imperial_i00"/>
    <set name="price" value="3760000"/>
    <set name="rnd_dam" value="0"/>
    <set name="soulshots" value="0"/>
    <set name="spiritshots" value="0"/>
    <set name="type" value="NONE"/>
    <set name="weight" value="1170"/>
    <equip>
      <slot id="LEFT_HAND"/>
    </equip>
    <for>
      <add stat="sDef" order="0x10" value="290"/>
      <add stat="rShld" order="0x10" value="20"/>
      <add stat="rEvas" order="0x10" value="-8.0000"/>
      <enchant stat="sDef" order="0x0C" value="0"/>
    </for>
  </weapon>
  	<weapon id="9401" name="Zombie Shield">
    <!-- [Zombie Shield] -->
    <set name="crystal_count" value="188"/>
    <set name="crystal_type" value="S"/>
    <set name="crystallizable" value="true"/>
    <set name="icon" value="Old_ShieldIcons.nephilim_i00"/>
    <set name="price" value="3760000"/>
    <set name="rnd_dam" value="0"/>
    <set name="soulshots" value="0"/>
    <set name="spiritshots" value="0"/>
    <set name="type" value="NONE"/>
    <set name="weight" value="1170"/>
    <equip>
      <slot id="LEFT_HAND"/>
    </equip>
    <for>
      <add stat="sDef" order="0x10" value="290"/>
      <add stat="rShld" order="0x10" value="20"/>
      <add stat="rEvas" order="0x10" value="-8.0000"/>
      <enchant stat="sDef" order="0x0C" value="0"/>
    </for>
  </weapon>                                                                                                               
  </list>
