=== BACSHOW/Lucera2-Java25/game/data/stats/player/gain_level/gain_level.dtd
<!ELEMENT list (gain)*>
<!ELEMENT gain (level)*>
<!ATTLIST gain
        class_id CDATA #REQUIRED>
<!ELEMENT level (#PCDATA)>
<!ATTLIST level
        cp CDATA #REQUIRED
        hp CDATA #REQUIRED
        mp CDATA #REQUIRED
        val CDATA #REQUIRED>
]>

=== BACSHOW/Lucera2-Java25/game/data/stats/player/gain_level/[23] plain_walker.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "gain_level.dtd">
<list>
    <gain class_id="23">
        <level val="1" hp="89.0" mp="30.0" cp="35.6"/>
        <level val="2" hp="101.74" mp="35.46" cp="40.696"/>
        <level val="3" hp="114.62" mp="40.98" cp="45.848"/>
        <level val="4" hp="127.64" mp="46.56" cp="51.056"/>
        <level val="5" hp="140.8" mp="52.2" cp="56.32"/>
        <level val="6" hp="154.1" mp="57.9" cp="61.64"/>
        <level val="7" hp="167.54" mp="63.66" cp="67.016"/>
        <level val="8" hp="181.12" mp="69.48" cp="72.448"/>
        <level val="9" hp="194.84" mp="75.36" cp="77.936"/>
        <level val="10" hp="208.7" mp="81.3" cp="83.48"/>
        <level val="11" hp="222.7" mp="87.3" cp="89.08"/>
        <level val="12" hp="236.84" mp="93.36" cp="94.736"/>
        <level val="13" hp="251.12" mp="99.48" cp="100.448"/>
        <level val="14" hp="265.54" mp="105.66" cp="106.216"/>
        <level val="15" hp="280.1" mp="111.9" cp="112.04"/>
        <level val="16" hp="294.8" mp="118.2" cp="117.92"/>
        <level val="17" hp="309.64" mp="124.56" cp="123.856"/>
        <level val="18" hp="324.62" mp="130.98" cp="129.848"/>
        <level val="19" hp="339.74" mp="137.46" cp="135.896"/>
        <level val="20" hp="355.0" mp="144.0" cp="142"/>
        <level val="21" hp="385.8" mp="153.9" cp="154.32"/>
        <level val="22" hp="416.88" mp="163.89" cp="166.752"/>
        <level val="23" hp="448.24" mp="173.97" cp="179.296"/>
        <level val="24" hp="479.88" mp="184.14" cp="191.952"/>
        <level val="25" hp="511.8" mp="194.4" cp="204.72"/>
        <level val="26" hp="544.0" mp="204.75" cp="217.6"/>
        <level val="27" hp="576.48" mp="215.19" cp="230.592"/>
        <level val="28" hp="609.24" mp="225.72" cp="243.696"/>
        <level val="29" hp="642.28" mp="236.34" cp="256.912"/>
        <level val="30" hp="675.6" mp="247.05" cp="270.24"/>
        <level val="31" hp="709.2" mp="257.85" cp="283.68"/>
        <level val="32" hp="743.08" mp="268.74" cp="297.232"/>
        <level val="33" hp="777.24" mp="279.72" cp="310.896"/>
        <level val="34" hp="811.68" mp="290.79" cp="324.672"/>
        <level val="35" hp="846.4" mp="301.95" cp="338.56"/>
        <level val="36" hp="881.4" mp="313.2" cp="352.56"/>
        <level val="37" hp="916.68" mp="324.54" cp="366.672"/>
        <level val="38" hp="952.24" mp="335.97" cp="380.896"/>
        <level val="39" hp="988.08" mp="347.49" cp="395.232"/>
        <level val="40" hp="1024.2" mp="359.1" cp="409.68"/>
        <level val="41" hp="1071.0" mp="378.6" cp="428.4"/>
        <level val="42" hp="1118.16" mp="398.25" cp="447.264"/>
        <level val="43" hp="1165.68" mp="418.05" cp="466.272"/>
        <level val="44" hp="1213.56" mp="438.0" cp="485.424"/>
        <level val="45" hp="1261.8" mp="458.1" cp="504.72"/>
        <level val="46" hp="1310.4" mp="478.35" cp="524.16"/>
        <level val="47" hp="1359.36" mp="498.75" cp="543.744"/>
        <level val="48" hp="1408.68" mp="519.3" cp="563.472"/>
        <level val="49" hp="1458.36" mp="540.0" cp="583.344"/>
        <level val="50" hp="1508.4" mp="560.85" cp="603.36"/>
        <level val="51" hp="1558.8" mp="581.85" cp="623.52"/>
        <level val="52" hp="1609.56" mp="603.0" cp="643.824"/>
        <level val="53" hp="1660.68" mp="624.3" cp="664.272"/>
        <level val="54" hp="1712.16" mp="645.75" cp="684.864"/>
        <level val="55" hp="1764.0" mp="667.35" cp="705.6"/>
        <level val="56" hp="1816.2" mp="689.1" cp="726.48"/>
        <level val="57" hp="1868.76" mp="711.0" cp="747.504"/>
        <level val="58" hp="1921.68" mp="733.05" cp="768.672"/>
        <level val="59" hp="1974.96" mp="755.25" cp="789.984"/>
        <level val="60" hp="2028.6" mp="777.6" cp="811.44"/>
        <level val="61" hp="2082.6" mp="800.1" cp="833.04"/>
        <level val="62" hp="2136.96" mp="822.75" cp="854.784"/>
        <level val="63" hp="2191.68" mp="845.55" cp="876.672"/>
        <level val="64" hp="2246.76" mp="868.5" cp="898.704"/>
        <level val="65" hp="2302.2" mp="891.6" cp="920.88"/>
        <level val="66" hp="2358.0" mp="914.85" cp="943.2"/>
        <level val="67" hp="2414.16" mp="938.25" cp="965.664"/>
        <level val="68" hp="2470.68" mp="961.8" cp="988.272"/>
        <level val="69" hp="2527.56" mp="985.5" cp="1011.02"/>
        <level val="70" hp="2584.8" mp="1009.35" cp="1033.92"/>
        <level val="71" hp="2642.4" mp="1033.35" cp="1056.96"/>
        <level val="72" hp="2700.36" mp="1057.5" cp="1080.14"/>
        <level val="73" hp="2758.68" mp="1081.8" cp="1103.47"/>
        <level val="74" hp="2817.36" mp="1106.25" cp="1126.94"/>
        <level val="75" hp="2876.4" mp="1130.85" cp="1150.56"/>
        <level val="76" hp="2935.8" mp="1155.6" cp="1174.32"/>
        <level val="77" hp="2995.56" mp="1180.5" cp="1198.22"/>
        <level val="78" hp="3055.68" mp="1205.55" cp="1222.27"/>
        <level val="79" hp="3116.16" mp="1230.75" cp="1246.46"/>
        <level val="80" hp="3177.0" mp="1256.1" cp="1270.8"/>
    </gain>
</list>
